[project]
name = "simplewalker"
version = "0.1.0"
requires-python = ">=3.11"
description = "Two-legged walking robot"
readme = "README.md"
dependencies = [
    "numpy>=2.0",
]

[project.optional-dependencies]
calibration = [
    "scipy>=1.13",
]

interactive_calibration = [
    "matplotlib>=3.9",
    "pillow>=9.3",
    "scipy>=1.13",
]


[tool.ruff]
include = ["calibrate/*.py"]
[tool.ruff.lint]
ignore = ["E702",  # Multiple statements on one line
          "I001"   # Import order. Sure, some organization is good, but this is ridiculous.
]
[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["filter.FilterParams"]


[tool.pytest]
minversion = "9.0"
testpaths = ["test/unittests/calibration_model_unittest.py", "test/unittests/filter_unittest.py"]
# other unit tests are unittest framework

[tool.coverage.run]
include = ["calibrate/filter.py", "calibrate/motor_model.py", "calibrate/calibrate_fileIO.py"]
[tool.coverage.report]
[tool.coverage.html]
directory = "data/htmlcov"
