# Run motor calibration with checked-in motor calibration data
name: Calibrate Motor

on:
  push:
    paths:
      - .github/workflows/calibrate-motor.yml
      - data/motortestdata.zip
      - calibrate/calibrate.py
      - calibrate/calibrate_cli.py
      - pyproject.toml

jobs:
  calibrate:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        include:
          - python-version: ""
            dependency-resolution: "highest"
          - python-version: "3.11"
            dependency-resolution: "lowest"
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            calibrate/calibrate.py
            calibrate/calibrate_cli.py
            pyproject.toml
            data/motortestdata.zip
          sparse-checkout-cone-mode: false
      - name: Unzip motor test data
        run: unzip -d data/ data/motortestdata.zip
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
          resolution-strategy: ${{ matrix.dependency-resolution }}
      - name: calibrate
        run: uv run --extra calibration calibrate/calibrate_cli.py data/*.motortest -m static_fric const_opposing_fric -o data/motorparams -T 0.12 >> $GITHUB_STEP_SUMMARY
